swagger: "2.0"
info:
  title: Payments API Demo
  description: A demo of RESTful API for CRUD operations on payments
  version: 0.1.0
  contact:
    email: web@rafalgolarz.com
schemes:
- http
tags:
- name: payments
  description: Show (all or by ID), Add, Update, Delete payment
host: localhost
basePath: /v1
paths:
  /payments:
    get:
      tags:
      - payments
      summary: Show all payments
      description: This can only be done by the logged in user.
      operationId: getPayments
      produces:
      - application/json
      responses:
        200:
          description: Success response
          schema:
            $ref: "#/definitions/Payments"
    post:
      tags:
      - payments
      summary: Add a new payment
      description: This can only be done by the logged in user.
      operationId: addPayment
      parameters:
      - name: body
        in: body
        description: Payment object that needs to be added
        schema:
          $ref: "#/definitions/Payment"
        required: true
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        405:
          description: Invalid input

  /payments/{paymentId}:
    get:
      tags:
      - payments
      summary: Find payment by ID
      description: This can only be done by the logged in user.
      operationId: getPaymentByID
      parameters:
      - name: paymentId
        in: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        200:
          description: Success response
          schema:
            $ref: "#/definitions/Payment"
        400:
          description: Invalid ID supplied
        404:
          description: Payment not found
    delete:
      tags:
      - payments
      summary: Delete payment by ID
      description: This can only be done by the logged in user.
      operationId: deletePaymentByID
      produces:
      - application/json
      parameters:
      - name: paymentId
        in: path
        description: The payment ID that needs to be deleted
        required: true
        type: string
      responses:
        400:
          description: Invalid paymentID supplied
        404:
          description: Payment not found
    put:
      tags:
      - payments
      summary: Update payment by ID
      description: This can only be done by the logged in user.
      operationId: updatePaymentByID
      produces:
      - application/json
      parameters:
      - name: paymentId
        in: path
        description: The payment ID that needs to be updated
        required: true
        type: string
      - name: body
        in: body
        description: Updated payment object
        required: true
        schema:
          $ref: "#/definitions/Payment"
      responses:
        400:
          description: Invalid paymentID supplied
        404:
          description: Payment not found
definitions:
  BeneficiaryParty:
    type: object
    properties:
      account_name:
        type: string
        description: Beneficiary account name
        example: John Rambo
      account_number:
        type: string
        description: Beneficiary account number
        example: 31926819
      account_number_code:
        type: string
        description: IBAN, BBAN, BIC, SEPA, ECB, SWIFT, EFTA
        example: IBAN
      address:
        type: string
        description: Beneficiary address
        example: 1 The Beneficiary Localtown SE2
      bank_id:
        type: string
        description: id reference to the list of banks
        example: 403000
      bank_id_code:
        type: string
        description: Clearing code (ISO20022)
        example: GBDSC
      name:
        type: string
        description: Beneficiary name (could be an organisation)
        example: Bruce Lee
  ChargesInformation:
    type: object
    properties:
      bearer_code:
        type: string
        description: Values according to ISO20022 (DEBT, CRED, SHAR, SLEV)
        example: SHAR
      sender_charges_amount:
        type: string
        description: Sender’s charges
        example: "5.00"
      sender_charges_currency:
        type: string
        description: Sender’s charges currency
        example: GBP
      receiver_charges_amount:
        type: string
        description: Amount charged
        example: "1.00"
      receiver_charges_currency:
        type: string
        description: Currency of the charged amount
        example: USD
  DebtorParty:
    type: object
    properties:
      account_name:
        type: string
        description: Debtor's account name
        example: Martin Sheen
      account_number:
        type: string
        description: Debtor's account number
        example: GB29XABC10161234567801
      account_number_code:
        type: string
        description: IBAN, BBAN, BIC, SEPA, ECB, SWIFT, EFTA
        example: IBAN
      address:
        type: string
        description: Debtor's address
        example: 10 Debtor Crescent Sourcetown NE1
      bank_id:
        type: string
        description: ID reference to the list of banks
        example: 203301
      bank_id_code:
        type: string
        description: Clearing code (ISO20022)
        example: GBDSC
      name:
        type: string
        description: Debtor's name (could be an organisation)
        example: Jacky Chan
  Fx:
    type: object
    properties:
      contract_reference:
        type: string
        description: Reference to the exchange contract
        example: FX123
      exchange_rate:
        type: string
        description: Exchange rate (5 digits after the decimal point)
        example: "2.00000"
      original_amount:
        type: string
        description: Sender’s amount converted to the receiver’s currency
        example: "200.42"
      original_currency:
        type: string
        description: Receiver’s currency
        example: USD
  Payment:
    type: object
    properties:
      type:
        type: string
        description: Resource type
        example: Payment
      id:
        type: string
        format: UUID
        description: Resource identifier (used in CRUD operations)
        example: 4ee3a8d8-ca7b-4290-a52c-dd5b6165ec43
      version:
        type: integer
        description: Version of the record (initially 0)
      organisation_id:
        type: string
        description: Organisation identifier
        example: 743d5b63-8e6f-432e-a8fa-c5d8d2ee5fcb
      amount:
        type: string
        description: Transaction value (decimal point)
        example: 12300.21
      beneficiary_party:
         $ref: "#/definitions/BeneficiaryParty"
      charges_information:
        $ref: "#/definitions/ChargesInformation"
      currency:
        type: string
        description: Original currency of the transaction (ISO4217)
        example: GBP
      debtor_party:
        $ref: "#/definitions/DebtorParty"
      fx:
        $ref: "#/definitions/Fx"
      payment_purpose:
        type: string
        description: Reason for transaction
        example: Paying for goods/services
      payment_type:
        type: string
        description: Direct Debit, Credit, etc
        example: Credit
      processing_date:
        type: string
        description: Payment will be debited from the debitor account on that date (YYYY-MM-DD)
        example: "2017-01-18"
  Payments:
    type: array
    items:
      $ref: "#/definitions/Payment"